### ISSUE TITLE
get_streaming example doesn't always work correctly

### ISSUE THREAD

**Issue by ghost** [SergejJurecko/mio_httpc#11]
get_streaming.rs example with "https://api.hitbtc.com/api/2/public/currency" url returns empty body, while browsers/hyper/reqwest return the full body.

**Comment by SergejJurecko** [comment]
Setting gzip(false) in builder should make it work. When using streaming response having gzip enabled does not make sense anyway because you can't do anything with the data until you have everything (only then can you extract it). I think I should set gzip(false) automatically when CallBuilder.call is used.

**Comment by ghost** [comment]
Great, thanks a lot for the clarification!
.gzip(false) works indeed.
