### ISSUE TITLE
thoughts on upgrading to mio v0.7

### ISSUE THREAD

**Issue by jstrong-tios** [SergejJurecko/mio_httpc#22]
I've used mio_httpc on past projects successfully and am planning to on another one currently. As part of my planning/review, I looked at whether the mio_httpc could be easily modified to accommodate the changes in mio's api between v0.6 and v0.7. After about an hour of trying to make the modifications myself, I gave up (at least temporarily). It seems that the changes are deep enough that it would require modifying the types that mio_httpc using internally to represent a connection, among many other things.

I am writing to inquire about whether you plan to modify mio_httpc in the near term to use mio's v0.7 api? The mio project authors have stated that mio v1.0 will have a similar api to v0.7. However, while the v0.7 api is arguably cleaner and simpler than v0.6, it brings no new significant functionality. There are no any advertised performance advantages to v0.7, either.

My conclusion from this review is that my current project will need to settle on using mio v0.6, which is not what I had hoped for, but will certainly work fine. Any thoughts you have on this would be greatly appreciated. Thanks again for your work on this excellent library!

**Comment by SergejJurecko** [comment]
For a while I had a hard requirement for 0.6 due to needing to ship on UWP. That is gone now. But I am however extremely busy atm. 0.7/1.0 will eventually be done as mio_httpc is a core part of what I do, but I can’t promise any timeframe.

**Comment by dvtomas** [comment]
I'm definitely looking forward migrating to 0.7.0, because these two issues are seriously harming the usability of MIO on windows for my use-cases:

https://github.com/tokio-rs/mio/issues/776

https://github.com/tokio-rs/mio/issues/919

Both are fixed in MIO 0.7 . I'm connecting to various measurement devices over TCP and UDP, and the leaked descriptors prohibit me from reconnecting in case of communication failure (already in use). I've managed to work around in the TCP case, but I can't solve the UDP case.

I probably could have two versions of mio - 0.7 for my use, and 0.6 for mio_httpc, but it would be much cleaner to have mio_httpc also upgraded.

**Comment by SergejJurecko** [comment]
Migrated
