### ISSUE TITLE
Have `CallBuilder` consume-by-value

### ISSUE THREAD

**Issue by sampersand** [SergejJurecko/mio_httpc#7]
According to the documentation on [`call`](https://docs.rs/mio_httpc/0.6.15/mio_httpc/struct.CallBuilder.html#method.call) (and `simple_call`), "CallBuilder is invalid after this call and will panic if used again". If using the `CallBuilder` again should be an invalid operation, why not make `call` a "by-value" function? That way, it's impossible for the user to use the `CallBuilder` struct again.

This would also allow you remove the `Option` part of the `cb` field as well
```rust
pub fn call(self, httpc: &mut Httpc, poll: &Poll) -> Result<Call> {
        httpc.call::<CONNECTOR>(self.cb, poll)
    }
}
```

**Comment by SergejJurecko** [comment]
This used to be the API but I changed it because it is annoying in a different way. If you make the builder in one go its fine. But if you require some logic in between building your call you must always assign it back. So it causes a bunch of let mut builder = builder.something(..) statements which I think is uglier.

**Comment by sampersand** [comment]
I personally like putting all my "setup" code at the beginning before creating any structs
